using Assets.Scripts.ActorComponents;
using UnityEngine;

namespace Assets.Scripts.SteeringBehaviours
{
    /// <summary>
    /// Abstract class. Steering Behaviours will inherit from this
    /// </summary>
    [RequireComponent(typeof(VehicleComponent))]
    public abstract class SteeringBehaviourBase : MonoBehaviour
    {
        [Tooltip("A reference to the Vehicle component on this gameObject")]
        protected VehicleComponent VehicleComponent;

        protected virtual void Awake()
        {
            if (!TryGetComponent(out VehicleComponent))
            {
                Debug.LogError("SteeringBehaviourBase::Awake() has failed - Could not locate Vehicle Component");
            }
        }

        //Needs to be overidden in child classes
        /// <summary>
        /// Calculate the force generated by this steering behaviour.
        /// </summary>
        /// <returns>The force generated by this steering behaviour.</returns>
        public abstract Vector3 Calculate();

    }
}
