using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Abstract class. Steering Behaviours will inherit from this (see Wander/Seek)
/// </summary>
[RequireComponent(typeof(Vehicle))]
public abstract class SteeringBehaviourBase : MonoBehaviour
{
    //Needs to be overidden in child classes
    /// <summary>
    /// Calculate the force generated by this steering behaviour.
    /// </summary>
    /// <returns>The force generated by this steering behaviour.</returns>
    public abstract Vector3 Calculate();

}
